version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9095:9095" # Map container's 9095 to host's 9095
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: springboot-mysql
      SERVER_PORT: 9095
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdb10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306" # Expose MySQL on default port
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
